/* tslint:disable */
/* eslint-disable */
/**
 * API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskModel } from './TaskModel';
import {
    TaskModelFromJSON,
    TaskModelFromJSONTyped,
    TaskModelToJSON,
    TaskModelToJSONTyped,
} from './TaskModel';

/**
 * 
 * @export
 * @interface BulkUpsertTasksModel
 */
export interface BulkUpsertTasksModel {
    /**
     * 
     * @type {Array<TaskModel>}
     * @memberof BulkUpsertTasksModel
     */
    tasks: Array<TaskModel>;
}

/**
 * Check if a given object implements the BulkUpsertTasksModel interface.
 */
export function instanceOfBulkUpsertTasksModel(value: object): value is BulkUpsertTasksModel {
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function BulkUpsertTasksModelFromJSON(json: any): BulkUpsertTasksModel {
    return BulkUpsertTasksModelFromJSONTyped(json, false);
}

export function BulkUpsertTasksModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpsertTasksModel {
    if (json == null) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskModelFromJSON)),
    };
}

export function BulkUpsertTasksModelToJSON(json: any): BulkUpsertTasksModel {
    return BulkUpsertTasksModelToJSONTyped(json, false);
}

export function BulkUpsertTasksModelToJSONTyped(value?: BulkUpsertTasksModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tasks': ((value['tasks'] as Array<any>).map(TaskModelToJSON)),
    };
}

